### PR TITLE
Moved pages in to a subfolder to clean it up

### PR DESCRIPTION
**Pull request by Jacalz**
Just moves the pages in to a simple folder named pages.
I did not know how to test this, but it should work I think :sweat_smile:

### CODE REVIEW

**Comment by spaam** [comment]
for some reason it fail 
https://travis-ci.org/spaam/svtplay-dl-web/builds/466163673?utm_source=github_status&utm_medium=notification  . did you try build it before pushing? :)

**Comment by Jacalz** [comment]
Didn't know what steps were required to build it :I

**Comment by granbom** [comment]
Usually in many jekyll sites I also move pages into a directory for a cleaner structure. I think however it's cleaner to have them under _pages instead of pages, to conform with the normal jekyll structure. 

Regardless you need to set permalink in front matter on the pages, othervise they will be located site.tld/pages/page/index.html

By default Jekyll process files in _data, _posts etc but not _pages, so `include: ["_pages"]` is needed in `_config.yml`

The error in this commit is only because internal links should have been changed to `pages/page.md` then it would have worked. Apart from that they would have been in e.g. svtplay-dl.se/pages/usage/index.html instead. That could have been fixed with permalink  on all pages, like I have done now in de22879b1d92b6beea789e4bac5c0a3bc443e364
But I think the structure is slightly cleaner if they are located under _pages instead like in this commit 1e33bfb835e1a2fe30858312137a5ccd54662c2d

Gott nytt år!

**Comment by Jacalz** [comment]
Okay, thanks for clarifying :+1: 
Gott nytt år på er också, hoppas 2019 blir ett riktigt bra år för svtplay-dl :fireworks:

**Pull request closed without merging**
